namenode-primary:
  image: akisys/hadoop:2.8.0
  ports:
    - "50070:50070"
  command: /entrypoint.sh hdfs namenode
  hostname: hdfs-namenode

namenode-secondary:
  image: akisys/hadoop:2.8.0
  command: /entrypoint.sh hdfs secondarynamenode
  ports:
    - "50090:50090"
  links:
    - namenode-primary:hdfs-namenode

datanode:
  image: akisys/hadoop:2.8.0
  command: /entrypoint.sh hdfs datanode
  ports:
    - "50075:50075"
  links:
    - namenode-primary:hdfs-namenode

resourcemanager:
  image: akisys/hadoop:2.8.0
  command: /entrypoint.sh yarn resourcemanager
  hostname: yarn-resourcemanager
  ports:
    - "8088:8088"

nodemanager:
  image: akisys/hadoop:2.8.0
  command: /entrypoint.sh yarn nodemanager
  links:
    - resourcemanager:yarn-resourcemanager
    - namenode-primary:hdfs-namenode
  ports:
    - "8042:8042"

historyserver:
  image: akisys/hadoop:2.8.0
  command: /entrypoint.sh mapred historyserver
  links:
    - namenode-primary:hdfs-namenode
  ports:
    - "19888:19888"
