version: "2"

services:
  namenode-primary:
    image: akisys/hadoop:2.8.0
    ports:
      - 50070:50070
    command: /entrypoint.sh hdfs namenode
    hostname: hdfs-namenode
    volumes:
      - /tmp/docker/hdfs:/hdfs
  namenode-secondary:
    image: akisys/hadoop:2.8.0
    command: /entrypoint.sh hdfs secondarynamenode
    ports:
      - 50090:50090
    depends_on:
      - namenode-primary
    links:
      - namenode-primary:hdfs-namenode
    volumes:
      - /tmp/docker/hdfs:/hdfs
  datanode:
    image: akisys/hadoop:2.8.0
    command: /entrypoint.sh hdfs datanode
    ports:
      - 50075:50075
    depends_on:
      - namenode-primary
    links:
      - namenode-primary:hdfs-namenode
    volumes:
      - /mnt/docker/hdfs:/hdfs
  resourcemanager:
    image: akisys/hadoop:2.8.0
    command: /entrypoint.sh yarn resourcemanager
    hostname: yarn-resourcemanager
    ports:
      - 8088:8088
    volumes:
      - /tmp/docker/hdfs:/hdfs
  nodemanager:
    image: akisys/hadoop:2.8.0
    command: /entrypoint.sh yarn nodemanager
    links:
      - resourcemanager:yarn-resourcemanager
      - namenode-primary:hdfs-namenode
    ports:
      - 8042:8042
    depends_on:
      - resourcemanager
      - namenode-primary
    volumes:
      - /tmp/docker/hdfs:/hdfs
  historyserver:
    image: akisys/hadoop:2.8.0
    command: /entrypoint.sh mapred historyserver
    links:
      - namenode-primary:hdfs-namenode
    ports:
      - 19888:19888
    depends_on:
      - namenode-primary
    volumes:
      - /tmp/docker/hdfs:/hdfs
